apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube-operator
  template:
    metadata:
      labels:
        name: sonarqube-operator
    spec:
      serviceAccountName: sonarqube-operator
      containers:
        - name: sonarqube-operator
          image: quay.io/jlfowle/sonarqube-operator:0.0.1
          command:
          - sonarqube-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sonarqube-operator"
